version: '2'

services:
  verdaccio:
    container_name: verdaccio-ldap
    build: verdaccio-ldap/
    ports:
      - "4873:4873"
    volumes:
      - "./storage:/verdaccio/storage"
      - "./conf:/verdaccio/conf"
volumes:
  verdaccio:
    driver: local
